### :x: 第一遍：null pointer exception没过
```
class Solution {
  public ListNode swapPairs(ListNode head) {
    ListNode dummy = new ListNode(0, head);
    ListNode cur = dummy;
    while(cur != null) {
      ListNode tmp = cur.next;
      ListNode tmp2 = cur.next.next.next;
      cur.next = cur.next.next;
      cur.next.next = tmp;
      cur.next.next.next = tmp2;
      cur = cur.next.next;
    }
    return dummy;
  }
}
```
tmp2的定义这一行报错了。我是参考解析里C的写法，写的java版。对比答案之后发现是循环控制条件写的不对，改成和答案一致的判断`cur.next`和`cur.next.next`之后，不报exception了，但是testcase过不了。发现我return出来的result在head的位置多一个0。这个错误应该是因为我在initialize dummy的时候给它赋值为0了。但是对比答案之后发现是我想错了，出现这个问题是因为我return了dummy，正确写法是`return dummy.next`

### :white_check_mark: 参考了答案（C的），改对了
```
class Solution {
  public ListNode swapPairs(ListNode head) {
    ListNode dummy = new ListNode(0, head);
    ListNode cur = dummy;
    while(cur.next != null && cur.next.next != null) {
      ListNode tmp = cur.next;
      ListNode tmp2 = cur.next.next.next;
      cur.next = cur.next.next;
      cur.next.next = tmp;
      cur.next.next.next = tmp2;
      cur = cur.next.next;
    }
    return dummy;
  }
}
```
